name: Deploy to Yandex Cloud S3

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install dependencies
        run: pnpm ci

      - name: Build project
        run: pnpm run build
        env:
          NODE_ENV: production

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS CLI for Yandex Cloud
        run: |
          aws configure set aws_access_key_id ${{ secrets.YC_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.YC_SECRET_ACCESS_KEY }}
          aws configure set region ru-central1

      - name: Deploy to Yandex Cloud S3
        run: |
          aws --endpoint-url=https://storage.yandexcloud.net s3 sync ./dist s3://${{ secrets.S3_BUCKET_NAME }} --delete --exclude "images/*" --exclude "travel-guides-data.json" --cache-control max-age=31536000,public
          aws --endpoint-url=https://storage.yandexcloud.net s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/index.html s3://${{ secrets.S3_BUCKET_NAME }}/index.html --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html
